# Dataset configuration
data:
  train_path: "data/train"
  test_path: "data/test"
  val_path: "data/val"  # divide test into test and val during model training 
  dataset_name: "35_odor_processed_data"
  num_classes: 35  # Update based on your dataset

# Transform configuration
transforms:
  grayscale: true
  normalize_mean: 0.5
  normalize_std: 0.5

# Dataloader configuration
dataloader:
  batch_size: 16
  num_workers: 2
  pin_memory: true


# Model configuration
model:
  name: "OdorCNN"
  input_channels: 1
  input_size: 256  # Adjust based on your actual image size
  dropout_rate: 0.3
